version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /contrib/telemetry/
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /contrib/gql/
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /contrib/polarismesh/
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /cmd/woco/
    schedule:
      interval: daily