version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: gomod
    directory: /contrib/telemetry/
    schedule:
      interval: monthly
  - package-ecosystem: gomod
    directory: /contrib/gql/
    schedule:
      interval: monthly
  - package-ecosystem: gomod
    directory: /contrib/polarismesh/
    schedule:
      interval: monthly
  - package-ecosystem: gomod
    directory: /cmd/woco/
    schedule:
      interval: monthly
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "*"
