spec: "petstore.yaml"
target: "petstore"
# external templates to execute
templateDir: "template"
models:
  UUID:
    model: github.com/google/uuid.UUID
  '#/components/schemas/ApiResponseXX':
    model: github.com/tsingsun/woocoo/cmd/woco/oasgen/internal/integration.ApiResponse