// Code generated by woco, DO NOT EDIT.

package petstore

import (
	"fmt"

	"github.com/gin-gonic/gin"
	"github.com/tsingsun/woocoo/cmd/woco/oasgen/internal/integration/extra"
)

// PetService is the server API for Pet service.
type PetService interface {
	// (POST /pet)
	AddPet(*gin.Context, *AddPetRequest) (*Pet, error)
	// (DELETE /pet/{petId})
	DeletePet(*gin.Context, *DeletePetRequest) error
	// (GET /pet/findByStatus)
	FindPetsByStatus(*gin.Context, *FindPetsByStatusRequest) ([]*Pet, error)
	// (GET /pet/findByTags)
	FindPetsByTags(*gin.Context, *FindPetsByTagsRequest) (Pets, error)
	// (GET /pet/{petId})
	GetPetById(*gin.Context, *GetPetByIdRequest) (*Pet, error)
	// (PUT /pet)
	UpdatePet(*gin.Context, *UpdatePetRequest) (*Pet, error)
	// (POST /pet/{petId})
	UpdatePetWithForm(*gin.Context, *UpdatePetWithFormRequest) error
	// (POST /pet/{petId}/uploadImage)
	UploadFile(*gin.Context, *UploadFileRequest) (*extra.ApiResponse, error)
}

// StoreService is the server API for Store service.
type StoreService interface {
	// (DELETE /store/order/{orderId})
	DeleteOrder(*gin.Context, *DeleteOrderRequest) error
	// (GET /store/inventory)
	GetInventory(*gin.Context) (map[string]int32, error)
	// (GET /store/order/{orderId})
	GetOrderById(*gin.Context, *GetOrderByIdRequest) (*Order, error)
	// (POST /store/order)
	PlaceOrder(*gin.Context, *PlaceOrderRequest) (*Order, error)
}

// UserService is the server API for User service.
type UserService interface {
	// (POST /user)
	CreateUser(*gin.Context, *CreateUserRequest) (*CreateUserResponse, error)
	// (POST /user/createWithArray)
	CreateUsersWithArrayInput(*gin.Context, *CreateUsersWithArrayInputRequest) error
	// (POST /user/createWithList)
	CreateUsersWithListInput(*gin.Context, *CreateUsersWithListInputRequest) error
	// (DELETE /user/{username})
	DeleteUser(*gin.Context, *DeleteUserRequest) error
	// (GET /user/{username})
	GetUserByName(*gin.Context, *GetUserByNameRequest) (*User, error)
	// (GET /user/login)
	LoginUser(*gin.Context, *LoginUserRequest) (string, error)
	// (GET /user/logout)
	LogoutUser(*gin.Context) error
	// (PUT /user/{username})
	UpdateUser(*gin.Context, *UpdateUserRequest) error
}

type UnimplementedPetService struct {
}

func (UnimplementedPetService) AddPet(c *gin.Context, req *AddPetRequest) (_ *Pet, err error) {
	err = fmt.Errorf("method AddPet not implemented")
	return
}

func (UnimplementedPetService) DeletePet(c *gin.Context, req *DeletePetRequest) (err error) {
	err = fmt.Errorf("method DeletePet not implemented")
	return
}

func (UnimplementedPetService) FindPetsByStatus(c *gin.Context, req *FindPetsByStatusRequest) (_ []*Pet, err error) {
	err = fmt.Errorf("method FindPetsByStatus not implemented")
	return
}

func (UnimplementedPetService) FindPetsByTags(c *gin.Context, req *FindPetsByTagsRequest) (_ Pets, err error) {
	err = fmt.Errorf("method FindPetsByTags not implemented")
	return
}

func (UnimplementedPetService) GetPetById(c *gin.Context, req *GetPetByIdRequest) (_ *Pet, err error) {
	err = fmt.Errorf("method GetPetById not implemented")
	return
}

func (UnimplementedPetService) UpdatePet(c *gin.Context, req *UpdatePetRequest) (_ *Pet, err error) {
	err = fmt.Errorf("method UpdatePet not implemented")
	return
}

func (UnimplementedPetService) UpdatePetWithForm(c *gin.Context, req *UpdatePetWithFormRequest) (err error) {
	err = fmt.Errorf("method UpdatePetWithForm not implemented")
	return
}

func (UnimplementedPetService) UploadFile(c *gin.Context, req *UploadFileRequest) (_ *extra.ApiResponse, err error) {
	err = fmt.Errorf("method UploadFile not implemented")
	return
}

type UnimplementedStoreService struct {
}

func (UnimplementedStoreService) DeleteOrder(c *gin.Context, req *DeleteOrderRequest) (err error) {
	err = fmt.Errorf("method DeleteOrder not implemented")
	return
}

func (UnimplementedStoreService) GetInventory(c *gin.Context) (_ map[string]int32, err error) {
	err = fmt.Errorf("method GetInventory not implemented")
	return
}

func (UnimplementedStoreService) GetOrderById(c *gin.Context, req *GetOrderByIdRequest) (_ *Order, err error) {
	err = fmt.Errorf("method GetOrderById not implemented")
	return
}

func (UnimplementedStoreService) PlaceOrder(c *gin.Context, req *PlaceOrderRequest) (_ *Order, err error) {
	err = fmt.Errorf("method PlaceOrder not implemented")
	return
}

type UnimplementedUserService struct {
}

func (UnimplementedUserService) CreateUser(c *gin.Context, req *CreateUserRequest) (_ *CreateUserResponse, err error) {
	err = fmt.Errorf("method CreateUser not implemented")
	return
}

func (UnimplementedUserService) CreateUsersWithArrayInput(c *gin.Context, req *CreateUsersWithArrayInputRequest) (err error) {
	err = fmt.Errorf("method CreateUsersWithArrayInput not implemented")
	return
}

func (UnimplementedUserService) CreateUsersWithListInput(c *gin.Context, req *CreateUsersWithListInputRequest) (err error) {
	err = fmt.Errorf("method CreateUsersWithListInput not implemented")
	return
}

func (UnimplementedUserService) DeleteUser(c *gin.Context, req *DeleteUserRequest) (err error) {
	err = fmt.Errorf("method DeleteUser not implemented")
	return
}

func (UnimplementedUserService) GetUserByName(c *gin.Context, req *GetUserByNameRequest) (_ *User, err error) {
	err = fmt.Errorf("method GetUserByName not implemented")
	return
}

func (UnimplementedUserService) LoginUser(c *gin.Context, req *LoginUserRequest) (_ string, err error) {
	err = fmt.Errorf("method LoginUser not implemented")
	return
}

func (UnimplementedUserService) LogoutUser(c *gin.Context) (err error) {
	err = fmt.Errorf("method LogoutUser not implemented")
	return
}

func (UnimplementedUserService) UpdateUser(c *gin.Context, req *UpdateUserRequest) (err error) {
	err = fmt.Errorf("method UpdateUser not implemented")
	return
}
