// Code generated by woco, DO NOT EDIT.

package petstore

import (
	"context"
	"fmt"

	"github.com/tsingsun/woocoo/cmd/woco/oasgen/internal/integration/extra"
)

// PetServer is the server API for Pet service.
type PetServer interface {
	// (POST /pet)
	AddPet(context.Context, *AddPetRequest) (*Pet, error)
	// (DELETE /pet/{petId})
	DeletePet(context.Context, *DeletePetRequest) error
	// (GET /pet/findByStatus)
	FindPetsByStatus(context.Context, *FindPetsByStatusRequest) ([]*Pet, error)
	// (GET /pet/findByTags)
	FindPetsByTags(context.Context, *FindPetsByTagsRequest) ([]*Pet, error)
	// (GET /pet/{petId})
	GetPetById(context.Context, *GetPetByIdRequest) (*Pet, error)
	// (PUT /pet)
	UpdatePet(context.Context, *UpdatePetRequest) (*Pet, error)
	// (POST /pet/{petId})
	UpdatePetWithForm(context.Context, *UpdatePetWithFormRequest) error
	// (POST /pet/{petId}/uploadImage)
	UploadFile(context.Context, *UploadFileRequest) (*extra.ApiResponse, error)
}

// StoreServer is the server API for Store service.
type StoreServer interface {
	// (DELETE /store/order/{orderId})
	DeleteOrder(context.Context, *DeleteOrderRequest) error
	// (GET /store/inventory)
	GetInventory(context.Context) (map[string]int32, error)
	// (GET /store/order/{orderId})
	GetOrderById(context.Context, *GetOrderByIdRequest) (*Order, error)
	// (POST /store/order)
	PlaceOrder(context.Context, *PlaceOrderRequest) (*Order, error)
}

// UserServer is the server API for User service.
type UserServer interface {
	// (POST /user)
	CreateUser(context.Context, *CreateUserRequest) error
	// (POST /user/createWithArray)
	CreateUsersWithArrayInput(context.Context) error
	// (POST /user/createWithList)
	CreateUsersWithListInput(context.Context) error
	// (DELETE /user/{username})
	DeleteUser(context.Context, *DeleteUserRequest) error
	// (GET /user/{username})
	GetUserByName(context.Context, *GetUserByNameRequest) (*User, error)
	// (GET /user/login)
	LoginUser(context.Context, *LoginUserRequest) (string, error)
	// (GET /user/logout)
	LogoutUser(context.Context) error
	// (PUT /user/{username})
	UpdateUser(context.Context, *UpdateUserRequest) error
}

type UnimplementedPetServer struct {
}

func (UnimplementedPetServer) AddPet(ctx context.Context, req *AddPetRequest) (_ *Pet, err error) {
	err = fmt.Errorf("method AddPet not implemented")
	return
}

func (UnimplementedPetServer) DeletePet(ctx context.Context, req *DeletePetRequest) (err error) {
	err = fmt.Errorf("method DeletePet not implemented")
	return
}

func (UnimplementedPetServer) FindPetsByStatus(ctx context.Context, req *FindPetsByStatusRequest) (_ []*Pet, err error) {
	err = fmt.Errorf("method FindPetsByStatus not implemented")
	return
}

func (UnimplementedPetServer) FindPetsByTags(ctx context.Context, req *FindPetsByTagsRequest) (_ []*Pet, err error) {
	err = fmt.Errorf("method FindPetsByTags not implemented")
	return
}

func (UnimplementedPetServer) GetPetById(ctx context.Context, req *GetPetByIdRequest) (_ *Pet, err error) {
	err = fmt.Errorf("method GetPetById not implemented")
	return
}

func (UnimplementedPetServer) UpdatePet(ctx context.Context, req *UpdatePetRequest) (_ *Pet, err error) {
	err = fmt.Errorf("method UpdatePet not implemented")
	return
}

func (UnimplementedPetServer) UpdatePetWithForm(ctx context.Context, req *UpdatePetWithFormRequest) (err error) {
	err = fmt.Errorf("method UpdatePetWithForm not implemented")
	return
}

func (UnimplementedPetServer) UploadFile(ctx context.Context, req *UploadFileRequest) (_ *extra.ApiResponse, err error) {
	err = fmt.Errorf("method UploadFile not implemented")
	return
}

type UnimplementedStoreServer struct {
}

func (UnimplementedStoreServer) DeleteOrder(ctx context.Context, req *DeleteOrderRequest) (err error) {
	err = fmt.Errorf("method DeleteOrder not implemented")
	return
}

func (UnimplementedStoreServer) GetInventory(ctx context.Context) (_ map[string]int32, err error) {
	err = fmt.Errorf("method GetInventory not implemented")
	return
}

func (UnimplementedStoreServer) GetOrderById(ctx context.Context, req *GetOrderByIdRequest) (_ *Order, err error) {
	err = fmt.Errorf("method GetOrderById not implemented")
	return
}

func (UnimplementedStoreServer) PlaceOrder(ctx context.Context, req *PlaceOrderRequest) (_ *Order, err error) {
	err = fmt.Errorf("method PlaceOrder not implemented")
	return
}

type UnimplementedUserServer struct {
}

func (UnimplementedUserServer) CreateUser(ctx context.Context, req *CreateUserRequest) (err error) {
	err = fmt.Errorf("method CreateUser not implemented")
	return
}

func (UnimplementedUserServer) CreateUsersWithArrayInput(ctx context.Context) (err error) {
	err = fmt.Errorf("method CreateUsersWithArrayInput not implemented")
	return
}

func (UnimplementedUserServer) CreateUsersWithListInput(ctx context.Context) (err error) {
	err = fmt.Errorf("method CreateUsersWithListInput not implemented")
	return
}

func (UnimplementedUserServer) DeleteUser(ctx context.Context, req *DeleteUserRequest) (err error) {
	err = fmt.Errorf("method DeleteUser not implemented")
	return
}

func (UnimplementedUserServer) GetUserByName(ctx context.Context, req *GetUserByNameRequest) (_ *User, err error) {
	err = fmt.Errorf("method GetUserByName not implemented")
	return
}

func (UnimplementedUserServer) LoginUser(ctx context.Context, req *LoginUserRequest) (_ string, err error) {
	err = fmt.Errorf("method LoginUser not implemented")
	return
}

func (UnimplementedUserServer) LogoutUser(ctx context.Context) (err error) {
	err = fmt.Errorf("method LogoutUser not implemented")
	return
}

func (UnimplementedUserServer) UpdateUser(ctx context.Context, req *UpdateUserRequest) (err error) {
	err = fmt.Errorf("method UpdateUser not implemented")
	return
}
