// Code generated by woco, DO NOT EDIT.

package petstore

import "github.com/gin-gonic/gin"

// PetServer is the server API for Pet service.
type PetServer interface {
	// (POST /pet)
	AddPet(c *gin.Context, req AddPetRequest) (Pet, error)
	// (DELETE /pet/{petId})
	DeletePet(c *gin.Context, req DeletePetRequest) error
	// (GET /pet/findByStatus)
	FindPetsByStatus(c *gin.Context, req FindPetsByStatusRequest) ([]Pet, error)
	// (GET /pet/findByTags)
	FindPetsByTags(c *gin.Context, req FindPetsByTagsRequest) ([]Pet, error)
	// (GET /pet/{petId})
	GetPetById(c *gin.Context, req GetPetByIdRequest) (Pet, error)
	// (PUT /pet)
	UpdatePet(c *gin.Context, req UpdatePetRequest) (Pet, error)
	// (POST /pet/{petId})
	UpdatePetWithForm(c *gin.Context, req UpdatePetWithFormRequest) error
	// (POST /pet/{petId}/uploadImage)
	UploadFile(c *gin.Context, req UploadFileRequest) (ApiResponse, error)
}

// StoreServer is the server API for Store service.
type StoreServer interface {
	// (DELETE /store/order/{orderId})
	DeleteOrder(c *gin.Context, req DeleteOrderRequest) error
	// (GET /store/inventory)
	GetInventory(c *gin.Context) (any, error)
	// (GET /store/order/{orderId})
	GetOrderById(c *gin.Context, req GetOrderByIdRequest) (Order, error)
	// (POST /store/order)
	PlaceOrder(c *gin.Context, req PlaceOrderRequest) (Order, error)
}

// UserServer is the server API for User service.
type UserServer interface {
	// (POST /user)
	CreateUser(c *gin.Context, req CreateUserRequest) error
	// (POST /user/createWithArray)
	CreateUsersWithArrayInput(c *gin.Context) error
	// (POST /user/createWithList)
	CreateUsersWithListInput(c *gin.Context) error
	// (DELETE /user/{username})
	DeleteUser(c *gin.Context, req DeleteUserRequest) error
	// (GET /user/{username})
	GetUserByName(c *gin.Context, req GetUserByNameRequest) (User, error)
	// (GET /user/login)
	LoginUser(c *gin.Context, req LoginUserRequest) (string, error)
	// (GET /user/logout)
	LogoutUser(c *gin.Context) error
	// (PUT /user/{username})
	UpdateUser(c *gin.Context, req UpdateUserRequest) error
}
