// Code generated by woco, DO NOT EDIT.

package petstore

import "time"

type ApiResponse struct {
	Code    int32  `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
	Type    string `json:"type,omitempty"`
}

type Category struct {
	ID   int64  `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}

type Order struct {
	Complete bool      `json:"complete,omitempty"`
	ID       int64     `json:"id,omitempty"`
	PetId    int64     `json:"petId,omitempty"`
	Quantity int32     `json:"quantity,omitempty"`
	ShipDate time.Time `json:"shipDate,omitempty"`
	Status   string    `json:"status,omitempty"`
}

type Pet struct {
	Category  *Category `json:"category,omitempty"`
	ID        int64     `json:"id,omitempty"`
	Name      string    `json:"name"`
	PhotoUrls []string  `json:"photoUrls"`
	Status    string    `json:"status,omitempty"`
	Tags      []Tag     `json:"tags,omitempty"`
}

type Tag struct {
	ID   int64  `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}

type User struct {
	Email      string `json:"email,omitempty"`
	FirstName  string `json:"firstName,omitempty"`
	ID         int64  `json:"id,omitempty"`
	LastName   string `json:"lastName,omitempty"`
	Password   string `json:"password,omitempty"`
	Phone      string `json:"phone,omitempty"`
	UserStatus int32  `json:"userStatus,omitempty"`
	Username   string `json:"username,omitempty"`
}
