// Code generated by woco, DO NOT EDIT.

package petstore

type AddPetRequest struct {
	Pet Pet `form:"Pet"`
}

type DeletePetRequest struct {
	APIKey string `header:"api_key"`
	PetId  int64  `uri:"petId" binding:"required"`
}

type FindPetsByStatusRequest struct {
	Status []string `form:"status" binding:"required"`
}

type FindPetsByTagsRequest struct {
	Tags []string `form:"tags" binding:"required"`
}

type GetPetByIdRequest struct {
	PetId int64 `uri:"petId" binding:"required"`
}

type UpdatePetRequest struct {
	Pet Pet `form:"Pet"`
}

type UpdatePetWithFormRequest struct {
	PetId  int64  `uri:"petId" binding:"required"`
	Name   string `form:"name"`
	Status string `form:"status"`
}

type UploadFileRequest struct {
	PetId              int64  `uri:"petId" binding:"required"`
	AdditionalMetadata string `form:"additionalMetadata"`
	File               string `form:"file"`
}
