// Code generated by woco, DO NOT EDIT.

package petstore

type DeleteOrderRequest struct {
	UriParams struct {
		OrderId string `binding:"required" uri:"orderId"`
	}
}

type GetOrderByIdRequest struct {
	UriParams struct {
		OrderId int64 `binding:"required" uri:"orderId"`
	}
}

type PlaceOrderRequest struct {
	Body struct {
		Order Order `json:"order,omitempty"`
	}
}
