// Code generated by woco, DO NOT EDIT.

package petstore

type DeleteOrderRequest struct {
	UriParams struct {
		OrderId string `binding:"required" uri:"orderId"`
	}
}

type GetOrderByIdRequest struct {
	UriParams struct {
		OrderId int64 `binding:"lte=5,gte=1,required" uri:"orderId"`
	}
}

type PlaceOrderRequest struct {
	Body struct {
		Order Order `binding:"required" json:"order"`
	}
}
