// Code generated by woco, DO NOT EDIT.

package petstore

type DeleteOrderRequest struct {
	OrderId string `uri:"orderId" binding:"required"`
}

type GetOrderByIdRequest struct {
	OrderId int64 `uri:"orderId" binding:"required"`
}

type PlaceOrderRequest struct {
	Order Order `form:"Order"`
}
