// Code generated by woco, DO NOT EDIT.

package petstore

type CreateUserRequest struct {
	User User `form:"User"`
}

type DeleteUserRequest struct {
	Username string `uri:"username" binding:"required"`
}

type GetUserByNameRequest struct {
	Username string `uri:"username" binding:"required"`
}

type LoginUserRequest struct {
	Username string `form:"username" binding:"required"`
	Password string `form:"password" binding:"required"`
}

type UpdateUserRequest struct {
	Username string `uri:"username" binding:"required"`
	User     User   `form:"User"`
}
