// Code generated by woco, DO NOT EDIT.

package petstore

type CreateUserRequest struct {
	Body struct {
		User User `binding:"required" json:"user"`
	}
}

type DeleteUserRequest struct {
	UriParams struct {
		Username string `binding:"required" uri:"username"`
	}
}

type GetUserByNameRequest struct {
	UriParams struct {
		Username string `binding:"required" uri:"username"`
	}
}

type LoginUserRequest struct {
	Body struct {
		Username string `binding:"required,regex=oas_pattern_0" form:"username"`
		Password string `binding:"required" form:"password" password:"true"`
	}
}

type UpdateUserRequest struct {
	UriParams struct {
		Username string `binding:"required" uri:"username"`
	}
	Body struct {
		User User `binding:"required" json:"user"`
	}
}
