// Code generated by woco, DO NOT EDIT.

package server

import (
	"regexp"

	"github.com/gin-gonic/gin/binding"
	"github.com/go-playground/validator/v10"
)

var (
	patternMap = map[string]*regexp.Regexp{
		"oas_pattern_0": regexp.MustCompile("^[a-zA-Z0-9]+[a-zA-Z0-9\\.\\-_]*[a-zA-Z0-9]+$"),
	}
	regexTag validator.Func = func(fl validator.FieldLevel) bool {
		field := fl.Field().String()
		if field == "" {
			return true
		}
		if regex, ok := patternMap[fl.Param()]; ok {
			match := regex.MatchString(field)
			return match
		}
		return true
	}
)

func RegisterValidator() {
	if v, ok := binding.Validator.Engine().(*validator.Validate); ok {
		v.RegisterValidation("regex", regexTag)
	}
}
