development: true
log:
  sole:
    level: debug
    disableCaller: true
    disableStacktrace: true
    encoding: json
    outputPaths:
      - stdout
    errorOutputPaths:
      - stderr
service:
  server:
    listen: "20000"
    location: /woocoo/service
    version: "1.0"
    engine:
      - unaryinterceptors:
          - trace:
          - logger:
          - recovery:
          - prometheus:
          - auth:
  registry:
    schema: etcd
    ttl: 60s
    tls:
      ssl_certificate: ""
      ssl_certificate_key: ""
    etcd:
      endpoints:
        - :2379
      dial-timeout: 3s
      dial-keep-alive-time: 30s
  prometheus:
    addr: 0.0.0.0:2222
