// Code generated by woco, DO NOT EDIT.

package petstore

import (
	"encoding/json"
	"fmt"

	"github.com/gin-gonic/gin"
	"github.com/tsingsun/woocoo/cmd/woco/oasgen/internal/integration/extra"
)

// PetService is the server API for Pet service.
type PetServer interface {
	// (POST /pet)
	AddPet(*gin.Context, *AddPetRequest) (*Pet, error)
	// (DELETE /pet/{petId})
	DeletePet(*gin.Context, *DeletePetRequest) error
	// FindPetsByStatus Multiple status values can be provided with comma separated strings
	// (GET /pet/findByStatus)
	FindPetsByStatus(*gin.Context, *FindPetsByStatusRequest) ([]*Pet, error)
	// FindPetsByTags Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
	// (GET /pet/findByTags)
	FindPetsByTags(*gin.Context, *FindPetsByTagsRequest) (Pets, error)
	// GetPetById Returns a single pet
	// (GET /pet/{petId})
	GetPetById(*gin.Context, *GetPetByIdRequest) (*Pet, error)
	// (PUT /pet)
	UpdatePet(*gin.Context, *UpdatePetRequest) (*Pet, error)
	// (POST /pet/{petId})
	UpdatePetWithForm(*gin.Context, *UpdatePetWithFormRequest) error
	// (POST /pet/{petId}/uploadImage)
	UploadFile(*gin.Context, *UploadFileRequest) (*extra.ApiResponse, error)
}

// StoreService is the server API for Store service.
type StoreServer interface {
	// DeleteOrder For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors
	// (DELETE /store/order/{orderId})
	DeleteOrder(*gin.Context, *DeleteOrderRequest) error
	// GetInventory Returns a map of status codes to quantities
	// (GET /store/inventory)
	GetInventory(*gin.Context) (map[string]int32, error)
	// GetOrderById For valid response try integer IDs with value <= 5 or > 10. Other values will generated exceptions
	// (GET /store/order/{orderId})
	GetOrderById(*gin.Context, *GetOrderByIdRequest) (*Order, error)
	// (POST /store/order)
	PlaceOrder(*gin.Context, *PlaceOrderRequest) (*Order, error)
}

// UserService is the server API for User service.
type UserServer interface {
	// CreateUser This can only be done by the logged in user.
	// (POST /user)
	CreateUser(*gin.Context, *CreateUserRequest) (*CreateUserResponse, error)
	// CreateUserProfile This can only be done by the logged in user.
	// (POST /user/profile)
	CreateUserProfile(*gin.Context, *CreateUserProfileRequest) (json.RawMessage, error)
	// (POST /user/createWithArray)
	CreateUsersWithArrayInput(*gin.Context, *CreateUsersWithArrayInputRequest) error
	// (POST /user/createWithList)
	CreateUsersWithListInput(*gin.Context, *CreateUsersWithListInputRequest) error
	// DeleteUser This can only be done by the logged in user.
	// (DELETE /user/{username})
	DeleteUser(*gin.Context, *DeleteUserRequest) error
	// (GET /user/{username})
	GetUserByName(*gin.Context, *GetUserByNameRequest) (*User, error)
	// (GET /user/login)
	LoginUser(*gin.Context, *LoginUserRequest) (string, error)
	// (GET /user/logout)
	LogoutUser(*gin.Context) error
	// UpdateUser This can only be done by the logged in user.
	// (PUT /user/{username})
	UpdateUser(*gin.Context, *UpdateUserRequest) error
}

type UnimplementedPetServer struct {
}

func (UnimplementedPetServer) AddPet(c *gin.Context, req *AddPetRequest) (_ *Pet, err error) {
	err = fmt.Errorf("method AddPet not implemented")
	return
}

func (UnimplementedPetServer) DeletePet(c *gin.Context, req *DeletePetRequest) (err error) {
	err = fmt.Errorf("method DeletePet not implemented")
	return
}

func (UnimplementedPetServer) FindPetsByStatus(c *gin.Context, req *FindPetsByStatusRequest) (_ []*Pet, err error) {
	err = fmt.Errorf("method FindPetsByStatus not implemented")
	return
}

func (UnimplementedPetServer) FindPetsByTags(c *gin.Context, req *FindPetsByTagsRequest) (_ Pets, err error) {
	err = fmt.Errorf("method FindPetsByTags not implemented")
	return
}

func (UnimplementedPetServer) GetPetById(c *gin.Context, req *GetPetByIdRequest) (_ *Pet, err error) {
	err = fmt.Errorf("method GetPetById not implemented")
	return
}

func (UnimplementedPetServer) UpdatePet(c *gin.Context, req *UpdatePetRequest) (_ *Pet, err error) {
	err = fmt.Errorf("method UpdatePet not implemented")
	return
}

func (UnimplementedPetServer) UpdatePetWithForm(c *gin.Context, req *UpdatePetWithFormRequest) (err error) {
	err = fmt.Errorf("method UpdatePetWithForm not implemented")
	return
}

func (UnimplementedPetServer) UploadFile(c *gin.Context, req *UploadFileRequest) (_ *extra.ApiResponse, err error) {
	err = fmt.Errorf("method UploadFile not implemented")
	return
}

type UnimplementedStoreServer struct {
}

func (UnimplementedStoreServer) DeleteOrder(c *gin.Context, req *DeleteOrderRequest) (err error) {
	err = fmt.Errorf("method DeleteOrder not implemented")
	return
}

func (UnimplementedStoreServer) GetInventory(c *gin.Context) (_ map[string]int32, err error) {
	err = fmt.Errorf("method GetInventory not implemented")
	return
}

func (UnimplementedStoreServer) GetOrderById(c *gin.Context, req *GetOrderByIdRequest) (_ *Order, err error) {
	err = fmt.Errorf("method GetOrderById not implemented")
	return
}

func (UnimplementedStoreServer) PlaceOrder(c *gin.Context, req *PlaceOrderRequest) (_ *Order, err error) {
	err = fmt.Errorf("method PlaceOrder not implemented")
	return
}

type UnimplementedUserServer struct {
}

func (UnimplementedUserServer) CreateUser(c *gin.Context, req *CreateUserRequest) (_ *CreateUserResponse, err error) {
	err = fmt.Errorf("method CreateUser not implemented")
	return
}

func (UnimplementedUserServer) CreateUserProfile(c *gin.Context, req *CreateUserProfileRequest) (_ json.RawMessage, err error) {
	err = fmt.Errorf("method CreateUserProfile not implemented")
	return
}

func (UnimplementedUserServer) CreateUsersWithArrayInput(c *gin.Context, req *CreateUsersWithArrayInputRequest) (err error) {
	err = fmt.Errorf("method CreateUsersWithArrayInput not implemented")
	return
}

func (UnimplementedUserServer) CreateUsersWithListInput(c *gin.Context, req *CreateUsersWithListInputRequest) (err error) {
	err = fmt.Errorf("method CreateUsersWithListInput not implemented")
	return
}

func (UnimplementedUserServer) DeleteUser(c *gin.Context, req *DeleteUserRequest) (err error) {
	err = fmt.Errorf("method DeleteUser not implemented")
	return
}

func (UnimplementedUserServer) GetUserByName(c *gin.Context, req *GetUserByNameRequest) (_ *User, err error) {
	err = fmt.Errorf("method GetUserByName not implemented")
	return
}

func (UnimplementedUserServer) LoginUser(c *gin.Context, req *LoginUserRequest) (_ string, err error) {
	err = fmt.Errorf("method LoginUser not implemented")
	return
}

func (UnimplementedUserServer) LogoutUser(c *gin.Context) (err error) {
	err = fmt.Errorf("method LogoutUser not implemented")
	return
}

func (UnimplementedUserServer) UpdateUser(c *gin.Context, req *UpdateUserRequest) (err error) {
	err = fmt.Errorf("method UpdateUser not implemented")
	return
}
