// Code generated by woco, DO NOT EDIT.

package petstore

import (
	"fmt"
)

// CreateUserRequest is the request object for (POST /user)
type CreateUserRequest struct {
	Email     string `binding:"omitempty,email" json:"email,omitempty" xml:"email"`
	FirstName string `json:"firstName,omitempty" xml:"firstName"`
	ID        int64  `json:"id,omitempty" xml:"id"`
	LastName  string `json:"lastName,omitempty" xml:"lastName"`
	Password  string `json:"password,omitempty" xml:"password"`
	Phone     string `json:"phone,omitempty" xml:"phone"`
	// UserStatus User Status
	UserStatus int32  `json:"user_status,omitempty" xml:"user_status"`
	Username   string `json:"username,omitempty" xml:"username"`
}

// CreateUserProfileRequest is the request object for (POST /user/profile)
type CreateUserProfileRequest struct {
}

// CreateUsersWithArrayInputRequest is the request object for (POST /user/createWithArray)
type CreateUsersWithArrayInputRequest struct {
}

// CreateUsersWithListInputRequest is the request object for (POST /user/createWithList)
type CreateUsersWithListInputRequest struct {
}

// DeleteUserRequest is the request object for (DELETE /user/{username})
type DeleteUserRequest struct {
	// Username The name that needs to be deleted
	Username string `binding:"required" uri:"username"`
}

// GetUserByNameRequest is the request object for (GET /user/{username})
type GetUserByNameRequest struct {
	// Username The name that needs to be fetched. Use user1 for testing.
	Username string `binding:"required" uri:"username"`
}

// LoginUserRequest is the request object for (GET /user/login)
type LoginUserRequest struct {
	// Username The user name for login
	Username string `binding:"required,regex=oas_pattern_0" form:"username"`
	// Password The password for login in clear text
	Password string `binding:"required" form:"password" password:"true"`
}

// TokenRequest is the request object for (POST /token)
type TokenRequest struct {
	ClientID     string    `binding:"required" form:"client_id"`
	ClientSecret string    `binding:"required" form:"client_secret"`
	GrantType    GrantType `binding:"required,oneof=client_credentials" form:"grant_type"`
}

// UpdateUserRequest is the request object for (PUT /user/{username})
type UpdateUserRequest struct {
	PathParams UpdateUserRequestPathParams
	Body       UpdateUserRequestBody
}

type UpdateUserRequestPathParams struct {
	// Username name that need to be deleted
	Username string `binding:"required" uri:"username"`
}

// UpdateUser This can only be done by the logged in user.
type UpdateUserRequestBody struct {
	Email     string `binding:"omitempty,email" json:"email,omitempty" xml:"email"`
	FirstName string `json:"firstName,omitempty" xml:"firstName"`
	ID        int64  `json:"id,omitempty" xml:"id"`
	LastName  string `json:"lastName,omitempty" xml:"lastName"`
	Password  string `json:"password,omitempty" xml:"password"`
	Phone     string `json:"phone,omitempty" xml:"phone"`
	// UserStatus User Status
	UserStatus int32  `json:"user_status,omitempty" xml:"user_status"`
	Username   string `json:"username,omitempty" xml:"username"`
}

// GrantType defines the type for the grant_type.grant_type enum field.
type GrantType string

// GrantType values.
const (
	GrantTypeClientCredentials GrantType = "client_credentials"
)

func (gt GrantType) String() string {
	return string(gt)
}

// GrantTypeValidator is a validator for the GrantType field enum values.
func GrantTypeValidator(gt GrantType) error {
	switch gt {
	case GrantTypeClientCredentials:
		return nil
	default:
		return fmt.Errorf("GrantType does not allow the value '%s'", gt)
	}
}

type TokenRequestBody struct {
	ClientID     string    `binding:"required" form:"client_id"`
	ClientSecret string    `binding:"required" form:"client_secret"`
	GrantType    GrantType `binding:"required,oneof=client_credentials" form:"grant_type"`
}

type TokenResponse struct {
	AccessToken string `json:"access_token,omitempty"`
	ExpiresIn   int    `json:"expires_in,omitempty"`
}

type CreateUserResponse struct {
	UserID string `json:"userID,omitempty"`
}
