// Code generated by woco, DO NOT EDIT.

package petstore

type DeleteOrderRequest struct {
	// OrderId ID of the order that needs to be deleted
	OrderId string `binding:"required" uri:"orderId"`
}

type GetOrderByIdRequest struct {
	// OrderId ID of pet that needs to be fetched
	OrderId int64 `binding:"lte=5,gte=1,required" uri:"orderId"`
}

// PlaceOrderRequest order placed for purchasing the pet
type PlaceOrderRequest struct {
	// PlaceOrderRequestBody An order for a pets from the pet store
	Order `json:",inline"`
}
