// Code generated by woco, DO NOT EDIT.

package petstore_expanded

import (
	"fmt"

	"github.com/gin-gonic/gin"
)

// Server is the server API for  service.
type Server interface {
	// (POST /pets)
	AddPet(*gin.Context, *AddPetRequest) (*Pet, error)
	// (DELETE /pets/{id})
	DeletePet(*gin.Context, *DeletePetRequest) error
	// (GET /pets/{id})
	FindPetByID(*gin.Context, *FindPetByIDRequest) (*Pet, error)
	// (GET /pets)
	FindPets(*gin.Context, *FindPetsRequest) ([]*Pet, error)
}

type UnimplementedServer struct {
}

func (UnimplementedServer) AddPet(c *gin.Context, req *AddPetRequest) (_ *Pet, err error) {
	err = fmt.Errorf("method AddPet not implemented")
	return
}

func (UnimplementedServer) DeletePet(c *gin.Context, req *DeletePetRequest) (err error) {
	err = fmt.Errorf("method DeletePet not implemented")
	return
}

func (UnimplementedServer) FindPetByID(c *gin.Context, req *FindPetByIDRequest) (_ *Pet, err error) {
	err = fmt.Errorf("method FindPetByID not implemented")
	return
}

func (UnimplementedServer) FindPets(c *gin.Context, req *FindPetsRequest) (_ []*Pet, err error) {
	err = fmt.Errorf("method FindPets not implemented")
	return
}
