// Code generated by woco, DO NOT EDIT.

package petstore_expanded

type Error struct {
	Code    int32  `binding:"required" json:"code"`
	Message string `binding:"required" json:"message"`
}
type NewPet struct {
	Name string `binding:"required" json:"name"`
	Tag  string `json:"tag,omitempty"`
}
type Pet struct {
	*NewPet `json:",inline"`
	ID      int64 `binding:"required" json:"id"`
}
