// Code generated by woco, DO NOT EDIT.

package petstore_expanded

type AddPetRequest struct {
	Body AddPetRequestBody
}
type AddPetRequestBody struct {
	NewPet *NewPet `binding:"required" json:"newPet"`
}

type DeletePetRequest struct {
	UriParams DeletePetRequestUriParams
}
type DeletePetRequestUriParams struct {
	ID int64 `binding:"required" uri:"id"`
}

type FindPetByIDRequest struct {
	UriParams FindPetByIDRequestUriParams
}
type FindPetByIDRequestUriParams struct {
	ID int64 `binding:"required" uri:"id"`
}

type FindPetsRequest struct {
	Body FindPetsRequestBody
}
type FindPetsRequestBody struct {
	Tags  []string `form:"tags"`
	Limit int32    `form:"limit"`
}
