name: GoTest

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - 'readme*.md'
      - 'contrib/**'
      - 'cmd/**'
      - '.github/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - 'readme*.md'
      - 'contrib/**'
      - 'cmd/**'
      - '.github/**'
jobs:
#  lint:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Run linters
#        uses: golangci/golangci-lint-action@v2.5.2
#        with:
#          version: v1.45.2

  build:
    runs-on: ubuntu-latest
    services:
      etcd:
        image: bitnami/etcd:3.4
        ports:
          - "2379:2379"
          - "2380:2380"
        env:
          ALLOW_NONE_AUTHENTICATION: yes
          ETCD_ADVERTISE_CLIENT_URLS: "http://127.0.0.1:2379"
    strategy:
      fail-fast: false
      matrix:
        go: ['1.18','1.19']
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Build
      run: go build -v ./...

    - name: Run coverage
      run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
